### ISSUE TITLE
[Epic] NEAR AI Developer Resources

### ISSUE THREAD

**Issue by gagdiez** [NEAR-DevHub/.github#14]
### Background

NEAR AI is one of the main initiatives currently in progress by NF, they are creating a registry of agents, models and benchmarks for everyone to create their own AI in a private and secure way

We need to help them by testing early versions of their tools, providing feedback and creating documentation and examples for other people to use it

### User Story

As a developer, I want to easily learn how to create agents, fine tune models and run benchmarks

As a developer I want to be able to create agents and share them, as well as use agents from other people

### Acceptance Criteria

- [ ] We create docs showing how to easily create agents, use models and run benchmarks
- [ ] We define at least 2 or 3 tutorials and create them showcasing interesting use cases of NEAR AI
- [ ] We create s blogpost and share it in our docs
- [ ] Create multimedia for all the previous

### Priority

🟠 P1 : High

**Comment by gagdiez** [comment]
Tracking our high level goal now in #26
